name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/build.yml'
      - 'modules/**'
      - 'static/**'
      - 'api.py'
      - 'pyproject.toml'
      - 'uv.lock'
  workflow_call:
    

jobs:
  build:
    if: github.repository == 'SubConv/SubConv'
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: [x64]
        include:
          - os: macos-latest
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: ${{ matrix.arch }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Dependencies
        run: |
          uv sync --locked --group build

      - name: Build Executable
        run: |
          uv run python -m nuitka --onefile api.py

      - name: Copy Files
        run: |
          mkdir output
          cp api${{ matrix.os == 'windows-latest' && '.exe' || '.bin' }} output/api${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          cp -r static output/static

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: subconv-${{ matrix.os }}-${{ matrix.arch }}
          path: output/
