name: Deploy Docs

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/deploy-docs.yml

env:
  TZ: Asia/Shanghai

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'SubConv/SubConv'
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.11
      - name: Install Dependencies
        run: bun ci
      - name: Build
        run: bun run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
