name: Test docs

on:
  workflow_dispatch: {}
  push:
    branches-ignore:
      - main
      - dev
    paths:
      - docs/**
      - .github/workflows/test-docs.yml
  pull_request:
    paths:
      - docs/**
      - .github/workflows/test-docs.yml

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'SubConv/SubConv'
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.11
      - name: Install Dependencies
        run: bun ci
      - name: Build
        run: bun run build
